export const JUST_ACTION="just_action";
export const FIRSTACTION="FIRSTACTION";
export const LOGIN_ACTION="LOGIN_ACTION";
export const SIGNUP_ACTION="SIGNUP_ACTION";

// FORM
export const APP_CREATOR_ACTION="APP_CREATOR_ACTION"